### ISSUE TITLE
Fatal error while cancelling subscription

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay-woocommerce#14]
Hello Team

Do you have any idea about the below fatal error? I am getting this error while canceling WooCommerce subscription.

```
[10-Oct-2022 11:48:41 UTC] PHP Fatal error:  Uncaught Exception: DateTimeImmutable::__construct(): Failed to parse time string (0) at position 0 (0): Unexpected character in C:\xampp\htdocs\wordpress-dev\wp-content\plugins\pronamic-ideal\vendor\wp-pay-extensions\woocommerce\src\SubscriptionUpdater.php:105
Stack trace:
#0 C:\xampp\htdocs\wordpress-dev\wp-content\plugins\pronamic-ideal\vendor\wp-pay-extensions\woocommerce\src\SubscriptionUpdater.php(105): DateTimeImmutable->__construct('0', Object(DateTimeZone))
#1 C:\xampp\htdocs\wordpress-dev\wp-content\plugins\pronamic-ideal\vendor\wp-pay-extensions\woocommerce\src\SubscriptionUpdater.php(203): Pronamic\WordPress\Pay\Extensions\WooCommerce\SubscriptionUpdater->update_pronamic_subscription()
#2 C:\xampp\htdocs\wordpress-dev\wp-includes\class-wp-hook.php(309): Pronamic\WordPress\Pay\Extensions\WooCommerce\SubscriptionUpdater::maybe_update_pronamic_subscription(2810)
#3 C:\xampp\htdocs\wordpress-dev\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 C:\xampp\htdocs\wordpress-dev\wp-includes\plugin.php(476): WP_Hook->do_action(Array)
#5 C:\xampp\htdocs\wordpress-dev\wp-includes\post.php(4662): do_action('save_post_shop_...', 2810, Object(WP_Post), true)
#6 C:\xampp\htdocs\wordpress-dev\wp-includes\post.php(4775): wp_insert_post(Array, false, true)
#7 C:\xampp\htdocs\wordpress-dev\wp-admin\includes\post.php(426): wp_update_post(Array)
#8 C:\xampp\htdocs\wordpress-dev\wp-admin\post.php(227): edit_post()
#9 {main}
  thrown in C:\xampp\htdocs\wordpress-dev\wp-content\plugins\pronamic-ideal\vendor\wp-pay-extensions\woocommerce\src\SubscriptionUpdater.php on line 105

```

**Comment by rvdsteege** [comment]
Seems the WooCommerce subscription has a trial period, but the trial end date is `0`?

https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/153e28ab41f629eb7d07ff921c5a6ac20d05ad38/src/SubscriptionUpdater.php#L99-L105
